### ISSUE TITLE
[Currybhari]-MAKING CONTROLLER IN ANGULAR

### ISSUE THREAD

**Issue by PANKAJKHANDKAR** [ankitzalani/currybhari-view#2]
**### Make controller for Index page which will control the Directives and Data passing between Index page and AngularJS Model Objects.
Initially Put Hard coded Json Data so that we just have to replace that Hard coded json with Real one e.g. [{'Indore Special','Sev',50}]**

**Comment by ankitzalani** [comment]
Added angular dependency.
